### ISSUE TITLE
ForwardEmail support of alt aliases: cannot set target when initially empty

### ISSUE THREAD

**Issue by yrodiere** [commonhaus/automation#202]
I'm getting multiple reports (from @lucamolteni and @jrenaat) that the member UI doesn't show any project alias for a contributor (non-member) to configure, even though that alias is set up correctly in the project.

Contributors see something like this:

<img width="786" height="216" alt="Image" src="https://github.com/user-attachments/assets/db650580-9db7-4bfa-981e-87ab3ac55bdd" />

It's missing the configured email, `luca@hibernate.org`.

Looking through haus-keeper logs, we have errors retrieving the alias from ForwardEmail:

```
2025-09-23 15:46:01,686 30aae38069b8 /work/application[1] DEBUG [org.com.aut.hk.for.ForwardEmailService] (executor-thread-104) getAliases: Alias not found: luca@hibernate.org
```

So evidently we're ending up in this case:

https://github.com/commonhaus/automation/blob/7f52153aa36271d0b0d830a2a085790eb56829cb/haus-keeper/src/main/java/org/commonhaus/automation/hk/forwardemail/ForwardEmailService.java#L65-L71

As far as I can see, the frontend would expect an alias to be returned in this case, though with empty data (no target, ...).

My theory is that one of these is happening:

1. there is some initialization of forwardemail that went wrong at some point, in such a way that the alias is considered valid on the Commonhaus side, but is not registered in Forwardemail.
2. OR the frontend is supposed to detect that some configured alias is not returned when calling `GET /member/aliases`, and call `POST /member/aliases` in that case to initialize data. But evidently, it doesn't.

At this point I think I'd love your help @ebullient -- which of the above is supposed to happen?

**Comment by ebullient** [comment]
yea.. I think I've fixed this one (or attempted to) several times. Let me try again. ;)

The good bit: it does know that they should have those aliases, and is attempting to find them.

Part of the problem is that past-history-me used a flag, and slightly-more-recent-history-me forgot what that flag was for (bad naming, and evolved idea of what it should be doing), and so now I have a gremlin running around in there because the two uses of that flag weren't quite the same.

**Comment by lucamolteni** [comment]
@ebullient any news on this? as of 2025-10-06 I still don't see the form to input the email to forward the alias to

<img width="830" height="488" alt="Image" src="https://github.com/user-attachments/assets/24d758de-b98a-4527-97c0-77dc6c860eea" />

**Comment by lucamolteni** [comment]
<img width="827" height="284" alt="Image" src="https://github.com/user-attachments/assets/7136153d-6201-4fdd-ae45-1d6ee1d200b1" />

Thank you!
